name: trigger jenkins job
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ vars.JENKINS_BASE_URL }}
          user: "suongnv"
          token: ${{ secrets.JENKINS_TOKEN_SUONGNV }}
          job: "demo-jenkins"